config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "/" => "citizens#index"

  resources :citizens

  post "/geocode" => "geocoder#geocode"
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/citizen.rb
class Citizen < ApplicationRecord
  has_one :address
  has_one_attached :avatar

  accepts_nested_attributes_for :address

  validates :name, :birthdate, :phone, presence: true
  validates :email, presence: true, format: URI::MailTo::EMAIL_REGEXP
  validate :valid_cpf

  scope :search_for, -> (string) do
    s = "%#{string}%"
    where("name ilike ? or phone ilike ? or cns ilike ? or cpf ilike ? or email ilike ?", s, s, s, s, s) if string.present?
  end

  scope :with_initial_date,
    lambda { |date|
      return unless date.present?
      where('birthdate >= ?', date)
    }

  scope :with_end_date,
    lambda { |date|
      return unless date.present?
      where('birthdate <= ?', date)
    }

  scope :with_status,
    lambda { |status|
      return unless status.present?
      where('status = ?', status)
    }

  def active?
    @active ||= status == "active"
  end

  def valid_cpf
    errors.add(:cpf, "deve ser válido") unless CPF.valid?(cpf, strict: true)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_page
    params[:page] || 1
  end
end

app/controllers/citizens_controller.rb
class CitizensController < ApplicationController
  before_action :set_citizen, only: [:edit, :update]

  def index
    @citizens = Citizen
                  .search_for(params[:q])
                  .with_initial_date(params[:initial_date])
                  .with_end_date(params[:end_date])
                  .with_status(params[:status])
                  .includes(:address)
                  .order(name: :asc)
                  .page(current_page)
  end

  def new
    @citizen = Citizen.new
    @citizen.build_address
  end

  def create
    @citizen = Citizen.new(form_params)

    if @citizen.save
      message = "Cadastro criado com sucesso!"

      CitizenMailer.new_message(
        citizen: @citizen,
        message: message
      ).deliver

      SmsMessageService.new(
        to: @citizen.phone,
        message: message
      ).send!

      redirect_to citizens_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    params = form_params.to_h
    different_status = @citizen.status != params[:status]

    if @citizen.update(params)
      message = "Seu cadastro foi atualizado para #{@citizen.active? ? "ativo" : "inativo"}"

      CitizenMailer.new_message(
        citizen: @citizen,
        message: message
      ).deliver if different_status

      SmsMessageService.new(
        to: @citizen.phone,
        message: message
      ).send! if different_status

      redirect_to citizens_path
    else
      render :edit
    end
  end

  private

  def form_params
    params.require(:citizen).permit(
      :name,
      :cpf,
      :cns,
      :email,
      :birthdate,
      :phone,
      :status,
      :avatar,
      address_attributes: [
        :id,
        :citizen_id,
        :cep,
        :street,
        :city,
        :state,
        :neighborhood,
        :number,
        :complement,
        :ibge_code
      ]
    )
  end

  def set_citizen
    @citizen = Citizen.find(params[:id])
  end
end

app/controllers/geocoder_controller.rb
class GeocoderController < ApplicationController
  protect_from_forgery with: :null_session

  def geocode
    result = Geocoder.search(params[:cep]).first

    render json: {
      city: result.sub_state,
      street: result.route,
      state: result.state_code,
      neighborhood: result.city
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/citizens/_form.html.erb
<div class="container mt-5">

<%= bootstrap_form_with(model: @citizen, local: true) do |f| %>

  <%= render('layouts/form_record_errors', record: @citizen) %>

  <div class="card">
    <div class="card-body">
      <div class="row">
        <div class="col-md-4">
          <%= f.text_field :name, label: "Nome", required: true %>
        </div>
        <div class="col-md-2">
          <%= f.text_field :cpf, label: "CPF", required: true %>
        </div>
        <div class="col-md-2">
          <%= f.text_field :cns, label: "CNS", required: true %>
        </div>
        <div class="col-md-4">
          <%= f.file_field :avatar %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <%= f.email_field :email, label: "Email", required: true %>
        </div>
        <div class="col-md-2">
          <%= f.text_field :phone, label: "Telefone", required: true %>
        </div>
        <div class="col-md-2">
          <%= f.date_field :birthdate, label: "Data de Nascimento", required: true %>
        </div>
        <div class="col-md-2">
          <% status_list = [["Ativo", "active"], ["Inativo", "inactive"]] %>
          <%= f.select(:status, options_for_select(status_list, selected: @citizen.status || "active"), include_blank: false) %>
        </div>
      </div>

      <p class="h5 mt-3 mb-3">Endereço</p>

      <%= f.fields_for :address do |a| %>
        <div class="row">
          <div class="col-md-2">
            <%= a.text_field :cep, label: "CEP", required: true %>
          </div>
          <div class="col-md-6">
            <%= a.text_field :street, label: "Logradouro", required: true %>
          </div>
          <div class="col-md-1">
            <%= a.text_field :number, label: "Número", required: true %>
          </div>
          <div class="col-md-3">
            <%= a.text_field :complement, label: "Complemento", required: false %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4">
            <%= a.text_field :city, label: "Cidade", required: true %>
          </div>
          <div class="col-md-2">
            <%= a.text_field :state, label: "UF", required: true %>
          </div>
          <div class="col-md-4">
            <%= a.text_field :neighborhood, label: "Bairro", required: true %>
          </div>
          <div class="col-md-2">
            <%= a.text_field :ibge_code, label: "Código IBGE", required: false %>
          </div>
        </div>

      <% end %>

      <br>
    <div class="card-footer d-flex justify-content-start mt-3">
      <%= f.submit("Salvar", class: 'btn btn-round btn-primary mr-4', data: {disable_with: "Aguarde"} ) %>
      <%= link_to("Voltar", citizens_path, class: 'btn btn-round btn-default') %>
    </div>
  </div>
<% end %>
</div>

app/views/citizens/edit.html.erb
<div class="container mt-5">

  <p class="h3 mb-5 mt-5">Editar Munícipe</p>

  <%= render('form', citizen: @citizen) %>

</div>

app/views/citizens/index.html.erb
<div class="container">

  <p class="h3 mb-5 mt-5">Munícipes</p>

  <%= link_to(new_citizen_path, class: 'btn btn-warning btn-md icon-btn mb-5') do %>
    Cadastrar Munícipe
  <% end %>

  <%= form_tag(citizens_path, method: :get) do |f| %>
    <div class="card bg-transparent mb-3">
      <div class="card-header">Filtros</div>
      <div class="card-body">
        <div class="row">
          <div class="col-md-4">
            <small>Nome, E-mail, Telefone, CPF ou CNS</small>
            <%= text_field_tag(:q, params[:q], class: "form-control") %>
          </div>
          <div class="col-md-2">
            <small>Data de nascimento inicial</small>
            <%= date_field("", :initial_date, class: 'form-control', value: params[:initial_date]) %>
          </div>
          <div class="col-md-2">
            <small>Data de nascimento final</small>
            <%= date_field("", :end_date, class: 'form-control', value: params[:end_date]) %>
          </div>
          <div class="col-md-2">
            <small>Situação</small>
            <% status_list = [["Ativo", "active"], ["Inativo", "inactive"]] %>
            <%= select_tag(:status, options_for_select(status_list, selected: params[:status]), include_blank: false, class: 'form-control') %>
          </div>
          <div class="col-md-2">
            <br>
            <button class="btn btn-outline-secondary btn-round" type="submit">
              <span class="fas fa-search"></span>
              Filtrar
            </button>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <div class="card">
    <table class="table card-table">
      <thead class="thead-light">
        <tr>
          <th>Nome</th>
          <th>CPF</th>
          <th>CNS</th>
          <th>Telefone</th>
          <th>E-mail</th>
          <th>Data de Nascimento</th>
          <th>Status</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @citizens.each do |citizen| %>
          <tr>
            <td><%= citizen.name  %></td>
            <td><%= citizen.cpf %></td>
            <td><%= citizen.cns %></td>
            <td><%= citizen.phone %></td>
            <td><%= citizen.email %></td>
            <td><%= citizen.birthdate.strftime("%d/%m/%Y") %></td>
            <td>
              <span class="badge text-bg-<%= citizen.active? ? "success" : "danger" %>">
                <%= citizen.active? ? "Ativo" : "Inativo" %>
              </span>
            </td>
            <td width='90px'>
              <button type="button" class="btn btn-light btn-sm icon-btn" data-bs-toggle="modal" data-bs-target="#myModal<%= citizen.id %>">
                Ver mais
              </button>

              <div class="modal fade" id="myModal<%= citizen.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h1 class="modal-title fs-5" id="exampleModalLabel">Dados de <%= citizen.name %></h1>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <div class="row">
                        <%= image_tag(citizen.avatar, class: "mb-4", style: "height:35%;width:35%;display:block;margin-left:auto;margin-right:auto;") if citizen.avatar.attached? %>
                      </div>
                      <% address = citizen.address %>
                      <div class="row">
                        <div class="col-md-6">
                            <small style="color:gray;">Logradouro</small><br>
                          <%= address.street %>
                        </div>
                        <div class="col-md-6">
                            <small style="color:gray;">Número</small><br>
                          <%= address.number %>
                        </div>
                      </div><br>
                      <div class="row">
                        <div class="col-md-6">
                            <small style="color:gray;">Complemento</small><br>
                          <%= address.complement %>
                        </div>
                        <div class="col-md-6">
                            <small style="color:gray;">CEP</small><br>
                          <%= address.cep %>
                        </div>
                      </div><br>
                      <div class="row">
                        <div class="col-md-6">
                            <small style="color:gray;">Bairro</small><br>
                          <%= address.neighborhood %>
                        </div>
                        <div class="col-md-6">
                            <small style="color:gray;">Cidade</small><br>
                          <%= address.city %>
                        </div>
                      </div><br>
                      <div class="row">
                        <div class="col-md-6">
                            <small style="color:gray;">UF</small><br>
                          <%= address.state %>
                        </div>
                        <div class="col-md-6">
                            <small style="color:gray;">Código IBGE</small><br>
                          <%= address.ibge_code %>
                        </div>
                      </div><br>
                      <div class="row">
                        <div class="col-md-6">
                            <small style="color:gray;">Criado em</small><br>
                          <%= address.created_at.strftime("%d/%m/%Y %H:%I") %>
                        </div>
                        <div class="col-md-6">
                            <small style="color:gray;">Atualizado em</small><br>
                          <%= address.updated_at.strftime("%d/%m/%Y %H:%I") %>
                        </div>
                      </div><br>
                    </div>
                  </div>
                </div>
              </div>

            </td>
            <td width='90px'>
              <%= link_to(edit_citizen_path(citizen), class: 'btn btn-primary btn-sm icon-btn') do %>
                Editar
              <% end %>
            </td>
          </tr>
        <% end %>
    </table>
  </div>

    <%= paginate @citizens %>

</div>

app/views/citizens/new.html.erb
<div class="container mt-5">

  <p class="h3 mb-5 mt-5">Cadastrar Munícipe</p>

  <%= render('form', citizen: @citizen) %>

</div>

app/views/layouts/_form_record_errors.html.erb
<% if record && record.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Desculpe! Não foi possível salvar:</h4>
    <ul>
    <% record.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Citizens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://unpkg.com/imask"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>